data:
  train: data/coco_trainval35k.json
  valid: data/coco_minival5k.json
params:
  batch_size: 12
  optimizer: Adam
  loss: focal
  lr: 1e-4
  epoch: 300
  lr_patience: -1
  lr_multistep: None
  random_seed: 3000
  image_size: 640x640 #rowsxcols
  classes: data/coco_classes.txt
  base: Res50
  pre_base: True
  num_crops: -1
  cls_threshold: 0.05
  data_worker: 6
inference:
  top_k: 1000
  resized: False
model:
  model_path: None
  exp_path: expr/pre_ex0
  is_finetune: False
cuda:
  using_cuda: False
  gpu_id: 0
